const { createPresentation } = require('./layout');
const { loadConfig } = require('./layout');

/**
 * 封面页生成器
 */
function createCoverSlide(pres, componentInfo, config) {
  const { colors, fonts } = config;
  const { name, type, filePath, description = '' } = componentInfo;
  
  const slide = pres.addSlide();
  
  // 背景色
  slide.background = { color: colors.background };
  
  // 标题区域装饰条
  slide.addShape(pres.shapes.RECTANGLE, {
    x: 0.5, y: 1.2, w: 9, h: 0.08,
    fill: { color: colors.primary }
  });
  
  // 组件类型标签
  slide.addText(type, {
    x: 0.5, y: 1.4, w: 2, h: 0.5,
    fontSize: 14, color: colors.primary,
    bold: false, align: 'left', valign: 'middle'
  });
  
  // 主标题
  slide.addText(name, {
    x: 0.5, y: 1.8, w: 9, h: 1.2,
    fontSize: 48, color: colors.text,
    bold: true, fontFace: fonts.title,
    align: 'left', valign: 'middle'
  });
  
  // 文件路径（小字）
  if (filePath) {
    const fileName = filePath.split('/').pop();
    slide.addText(`📁 ${fileName}`, {
      x: 0.5, y: 3.0, w: 4, h: 0.4,
      fontSize: 11, color: '666666',
      align: 'left', valign: 'middle'
    });
  }
  
  // 描述
  if (description) {
    slide.addText(description, {
      x: 0.5, y: 3.6, w: 9, h: 1.0,
      fontSize: 16, color: '666666',
      align: 'left', valign: 'middle'
    });
  }
  
  // 底部信息
  slide.addText(`Generated by React to PPT`, {
    x: 0.5, y: 5.5, w: 8, h: 0.3,
    fontSize: 9, color: '999999',
    align: 'right', valign: 'middle'
  });
  
  return slide;
}

/**
 * 代码页生成器 - 显示源代码
 */
function createCodeSlide(pres, componentInfo, config) {
  const { colors, fonts, highlight } = config;
  const { name, jsxElements, hooks, code } = componentInfo;
  
  const slide = pres.addSlide();
  
  // 标题栏
  slide.background = { color: colors.primary };
  
  slide.addText('📄 Code: ' + name, {
    x: 0.5, y: 0.4, w: 8, h: 0.6,
    fontSize: 20, color: colors.accent,
    bold: true, fontFace: fonts.title,
    align: 'left', valign: 'middle'
  });
  
  // 代码内容区域（简化版，实际需高亮）
  if (code) {
    const lines = code.split('\n').slice(0, 30); // 限制行数
    
    slide.addText('(Source code)', {
      x: 0.5, y: 1.5, w: 8, h: 4,
      fontSize: 10, color: colors.text,
      fontFace: fonts.code,
      align: 'left', valign: 'top'
    });
  }
  
  return slide;
}

/**
 * 组件结构页 - JSX 结构树
 */
function createStructureSlide(pres, componentInfo, config) {
  const { colors, fonts } = config;
  const { name, jsxElements } = componentInfo;
  
  const slide = pres.addSlide();
  
  slide.background = { color: colors.background };
  
  slide.addText('🏗️ Structure', {
    x: 0.5, y: 0.4, w: 9, h: 0.6,
    fontSize: 20, color: colors.primary,
    bold: true, fontFace: fonts.title,
    align: 'left', valign: 'middle'
  });
  
  // 绘制组件树
  const startY = 1.2;
  let currentY = startY;
  
  // 根节点框
  slide.addShape(pres.shapes.RECTANGLE, {
    x: 4, y: currentY, w: 2, h: 0.6,
    fill: { color: colors.primary }, line: { color: colors.primary, width: 2 }
  });
  
  slide.addText(name, {
    x: 4, y: currentY, w: 2, h: 0.6,
    fontSize: 14, color: colors.accent,
    align: 'center', valign: 'middle'
  });
  
  // 子元素列表
  if (jsxElements && jsxElements.length > 0) {
    const maxShow = Math.min(jsxElements.length, 12);
    jsxElements.slice(0, maxShow).forEach((el, idx) => {
      currentY += 0.7;
      
      // 子元素框
      slide.addShape(pres.shapes.RECTANGLE, {
        x: 5.5, y: currentY, w: 1.5, h: 0.5,
        fill: { color: colors.secondary }, line: { color: colors.secondary, width: 1 }
      });
      
      slide.addText(el.tag, {
        x: 5.5, y: currentY, w: 1.5, h: 0.5,
        fontSize: 10, color: colors.text,
        align: 'center', valign: 'middle'
      });
      
      // 连线
      slide.addShape(pres.shapes.LINE, {
        x: 4.9, y: currentY + 0.25, w: 0.6, h: 0,
        line: { color: colors.primary, width: 1 }
      });
    });
  }
  
  return slide;
}

/**
 * Props 表格页
 */
function createPropsSlide(pres, componentInfo, config) {
  const { colors, fonts } = config;
  const { name, props } = componentInfo;
  
  const slide = pres.addSlide();
  
  slide.background = { color: colors.background };
  
  slide.addText('📋 Props Table', {
    x: 0.5, y: 0.4, w: 9, h: 0.6,
    fontSize: 20, color: colors.primary,
    bold: true, fontFace: fonts.title,
    align: 'left', valign: 'middle'
  });
  
  // 表格标题
  slide.addText('Component: ' + name, {
    x: 0.5, y: 1.1, w: 9, h: 0.4,
    fontSize: 12, color: colors.text,
    align: 'left', valign: 'middle'
  });
  
  if (props && props.length > 0) {
    // 表格头部
    const headers = ['Prop Name', 'Type', 'Required', 'Default'];
    const colX = [0.5, 2.5, 5.5, 7.5];
    const colW = [2, 3, 1.5, 2];
    
    // 表头背景
    slide.addShape(pres.shapes.RECTANGLE, {
      x: 0.5, y: 1.8, w: 8.5, h: 0.5,
      fill: { color: colors.primary }, line: { color: colors.primary, width: 0 }
    });
    
    headers.forEach((header, idx) => {
      slide.addText(header, {
        x: colX[idx], y: 1.8, w: colW[idx], h: 0.5,
        fontSize: 11, color: colors.accent,
        bold: true, align: 'center', valign: 'middle'
      });
    });
    
    // 表格行
    props.forEach((prop, rowIdx) => {
      const y = 2.4 + rowIdx * 0.6;
      
      // 斑马纹
      if (rowIdx % 2 === 1) {
        slide.addShape(pres.shapes.RECTANGLE, {
          x: 0.5, y: y, w: 8.5, h: 0.5,
          fill: { color: 'F7F7F7' }
        });
      }
      
      slide.addText(prop.name || '...', {
        x: colX[0], y: y, w: colW[0], h: 0.5,
        fontSize: 10, color: colors.text,
        align: 'left', valign: 'middle', margin: { left: 0.1 }
      });
      
      slide.addText(prop.type || 'any', {
        x: colX[1], y: y, w: colW[1], h: 0.5,
        fontSize: 9, color: '666666',
        align: 'left', valign: 'middle'
      });
      
      slide.addText(prop.required ? 'Yes' : 'No', {
        x: colX[2], y: y, w: colW[2], h: 0.5,
        fontSize: 9, color: colors.text,
        align: 'center', valign: 'middle'
      });
      
      if (prop.default) {
        slide.addText(String(prop.default), {
          x: colX[3], y: y, w: colW[3], h: 0.5,
          fontSize: 9, color: '666666',
          align: 'left', valign: 'middle'
        });
      }
    });
  }
  
  return slide;
}

/**
 * Hooks 使用情况页
 */
function createHooksSlide(pres, componentInfo, config) {
  const { colors, fonts } = config;
  const { name, hooks, state } = componentInfo;
  
  const slide = pres.addSlide();
  
  slide.background = { color: colors.background };
  
  slide.addText('🪝 Hooks Usage', {
    x: 0.5, y: 0.4, w: 9, h: 0.6,
    fontSize: 20, color: colors.primary,
    bold: true, fontFace: fonts.title,
    align: 'left', valign: 'middle'
  });
  
  // 分两栏显示
  const col1X = 0.5;
  const col2X = 5.0;
  const cellW = 4.2;
  const cellH = 0.5;
  const startY = 1.2;
  
  // 左侧：Custom Hooks
  slide.addShape(pres.shapes.RECTANGLE, {
    x: col1X, y: startY - 0.2, w: cellW, h: 0.4,
    fill: { color: colors.secondary }
  });
  slide.addText('Custom Hooks', {
    x: col1X, y: startY - 0.2, w: cellW, h: 0.4,
    fontSize: 11, color: colors.primary,
    bold: true, align: 'center', valign: 'middle'
  });
  
  // 右侧：State & Effects
  slide.addShape(pres.shapes.RECTANGLE, {
    x: col2X, y: startY - 0.2, w: cellW, h: 0.4,
    fill: { color: colors.secondary }
  });
  slide.addText('State & Effects', {
    x: col2X, y: startY - 0.2, w: cellW, h: 0.4,
    fontSize: 11, color: colors.primary,
    bold: true, align: 'center', valign: 'middle'
  });
  
  // 填充自定义 Hooks
  const customHooks = hooks.filter(h => h.name !== 'useState' && h.name !== 'useEffect');
  customHooks.forEach((hook, idx) => {
    const y = startY + idx * 0.7;
    slide.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: col1X, y: y, w: cellW, h: 0.55,
      fill: { color: colors.background },
      line: { color: colors.primary, width: 1 }
    });
    slide.addText(hook.name, {
      x: col1X, y: y, w: cellW, h: 0.55,
      fontSize: 10, color: colors.text,
      align: 'left', valign: 'middle', margin: { left: 0.1 }
    });
  });
  
  // 填充 State & Effects
  const stateItems = state.slice(0, 6);
  stateItems.forEach((item, idx) => {
    const y = startY + idx * 0.7;
    slide.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x: col2X, y: y, w: cellW, h: 0.55,
      fill: { color: colors.background },
      line: { color: colors.primary, width: 1 }
    });
    slide.addText(`${item.hook || item.name}: ${item.type || ''}`, {
      x: col2X, y: y, w: cellW, h: 0.55,
      fontSize: 9, color: colors.text,
      align: 'left', valign: 'middle', margin: { left: 0.1 }
    });
  });
  
  return slide;
}

/**
 * 总结页
 */
function createSummarySlide(pres, componentInfo, config) {
  const { colors, fonts } = config;
  const { name, hooks, state, props } = componentInfo;
  
  const slide = pres.addSlide();
  slide.background = { color: colors.primary };
  
  slide.addText('✨ Key Takeaways', {
    x: 0.5, y: 0.8, w: 9, h: 0.8,
    fontSize: 28, color: colors.accent,
    bold: true, fontFace: fonts.title,
    align: 'center', valign: 'middle'
  });
  
  // 统计信息（大号数字）
  const stats = [
    { label: 'Hooks', value: hooks.length.toString() },
    { label: 'State', value: state.length.toString() },
    { label: 'Props', value: props.length.toString() }
  ];
  
  stats.forEach((stat, idx) => {
    const x = 1.5 + idx * 2.5;
    slide.addShape(pres.shapes.ROUNDED_RECTANGLE, {
      x, y: 2.2, w: 2, h: 1.5,
      fill: { color: colors.accent }
    });
    slide.addText(stat.value, {
      x, y: 2.2, w: 2, h: 0.8,
      fontSize: 48, color: colors.primary,
      bold: true, align: 'center', valign: 'middle'
    });
    slide.addText(stat.label, {
      x, y: 3.0, w: 2, h: 0.4,
      fontSize: 12, color: colors.text,
      align: 'center', valign: 'middle'
    });
  });
  
  // 组件名称
  slide.addText(`Component: ${name}`, {
    x: 0.5, y: 4.2, w: 9, h: 0.5,
    fontSize: 16, color: colors.accent,
    align: 'center', valign: 'middle'
  });
  
  return slide;
}

module.exports = {
  createCoverSlide,
  createCodeSlide,
  createStructureSlide,
  createPropsSlide,
  createHooksSlide,
  createSummarySlide
};
